/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-09-12 06:08:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jimin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"people_info section _people_info people_spc\"\r\n");
      out.write("		id=\"people_info_z\" data-dss-logarea=\"x29\">\r\n");
      out.write("		<div class=\"section_head\">\r\n");
      out.write("			<h2>인물 정보</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"cont_noline\" style=\"z-index: 10\">\r\n");
      out.write("			<div class=\"profile_wrap\">\r\n");
      out.write("				<div class=\"big_thumb\">\r\n");
      out.write("					<a nocr=\"\"\r\n");
      out.write("						onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.image&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("						href=\"https://search.naver.com/search.naver?where=image&amp;query=%EB%B0%A9%ED%83%84%EC%86%8C%EB%85%84%EB%8B%A8+%EC%A7%80%EB%AF%BC&amp;merge=0&amp;res_fr=0&amp;res_to=0&amp;sort=0&amp;viewtype=0&amp;site=&amp;face=1&amp;color=0&amp;mcs=0&amp;a_q=&amp;n_q=&amp;o_q=&amp;sm=tab_etc\"><img\r\n");
      out.write("						src=\"https://search.pstatic.net/common?type=a&amp;size=120x150&amp;quality=95&amp;direct=true&amp;src=http%3A%2F%2Fsstatic.naver.net%2Fpeople%2Fportrait%2F202002%2F20200213002028746.jpg\"\r\n");
      out.write("						alt=\"가수 지민 이미지\" width=\"120\" height=\"150\"\r\n");
      out.write("						onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"></a>\r\n");
      out.write("					<a nocr=\"\"\r\n");
      out.write("						onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.edit&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("						class=\"btn_profile_update\" href=\"http://myprofile.naver.com\"\r\n");
      out.write("						target=\"_blank\"><span class=\"blind\">가수 지민</span>내 인물정보 수정</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<dl class=\"detail_profile\">\r\n");
      out.write("					<dd class=\"name\">\r\n");
      out.write("						<a nocr=\"\"\r\n");
      out.write("							onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.namepeople&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("							href=\"https://people.search.naver.com/search.naver?where=nexearch&amp;query=%EC%A7%80%EB%AF%BC&amp;sm=tab_etc&amp;ie=utf8&amp;key=PeopleService&amp;os=585549\"\r\n");
      out.write("							target=\"_blank\"><strong>지민</strong></a> <span class=\"name_more\">(박지민)</span>\r\n");
      out.write("						<span>가수</span>\r\n");
      out.write("					</dd>\r\n");
      out.write("					<dt>출생</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<span> 1995년 10월 13일</span>\r\n");
      out.write("					</dd>\r\n");
      out.write("					<dt>소속그룹</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<a nocr=\"\"\r\n");
      out.write("							onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.group&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("							href=\"?where=nexearch&amp;sm=tab_etc&amp;mra=bjky&amp;pkid=1&amp;os=585527&amp;query=%EB%B0%A9%ED%83%84%EC%86%8C%EB%85%84%EB%8B%A8\">방탄소년단</a>\r\n");
      out.write("					</dd>\r\n");
      out.write("					<dt>소속사</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<a nocr=\"\"\r\n");
      out.write("							onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.management&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("							href=\"?where=nexearch&amp;sm=tab_etc&amp;query=%EB%B9%85%ED%9E%88%ED%8A%B8%20%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B8%EB%A8%BC%ED%8A%B8\">빅히트\r\n");
      out.write("							엔터테인먼트</a>\r\n");
      out.write("					</dd>\r\n");
      out.write("					<dt>데뷔</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<span>2013년 방탄소년단 싱글 앨범 [2 COOL 4 SKOOL]</span>\r\n");
      out.write("					</dd>\r\n");
      out.write("					<dt>수상</dt>\r\n");
      out.write("					<dd>2018년 화관문화훈장</dd>\r\n");
      out.write("					<dt>사이트</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<a nocr=\"\"\r\n");
      out.write("							onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.officialsite&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("							href=\"http://bts.ibighit.com\" target=\"_blank\">공식홈페이지</a>, <a\r\n");
      out.write("							nocr=\"\"\r\n");
      out.write("							onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.vlive&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("							href=\"http://www.vlive.tv/channels/FE619\" target=\"_blank\">V\r\n");
      out.write("							LIVE</a>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"go_relate\">\r\n");
      out.write("			<div class=\"offer_more2\">\r\n");
      out.write("				<div class=\"confirm\">\r\n");
      out.write("					<em>본인참여</em> 2020.02.14. <a nocr=\"\" href=\"javascript:;\"\r\n");
      out.write("						id=\"more_div_btn\"><img\r\n");
      out.write("						src=\"https://ssl.pstatic.net/sstatic/search/img/ico_help.gif\"\r\n");
      out.write("						width=\"12\" height=\"12\" alt=\"네이버 인물정보 도움말\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"left: -65px; width: 286px; visibility: hidden;\"\r\n");
      out.write("					class=\"layer_tooltip_wrap\" id=\"tooltip_layer\">\r\n");
      out.write("					<div class=\"layer_tooltip2\">\r\n");
      out.write("						<div class=\"content\">\r\n");
      out.write("							<p>\r\n");
      out.write("								네이버 인물검색은 당사자 본인이 제공한 자료 또는 언론 보도 등 일반에 공개된 자료를 바탕으로 인물정보를\r\n");
      out.write("								제공합니다.<br>인물정보의 당사자 본인은 직접 또는 대리인을 통해 언제든지 네이버에 수정 또는 삭제를\r\n");
      out.write("								신청하실 수 있으며 본인 또는 그 대리인의 마지막 수정요청이 처리된 날짜가 본인참여 일자로 표시·제공됩니다.<br>네이버는\r\n");
      out.write("								인물 본인이 제공하거나 일반에 공개된 자료를 매개 서비스하는 제공자로서 해당 정보의 정확성, 신뢰성 또는 최신성을\r\n");
      out.write("								보증하지 않습니다.<br>\r\n");
      out.write("								<br>\r\n");
      out.write("							</p>\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.imaginfmy&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								href=\"https://myprofile.naver.com/Main.nhn\" class=\"request\"\r\n");
      out.write("								target=\"_blank\">인물정보 수정신청</a>, <a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.imaginfcs&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								href=\"https://help.naver.com/support/alias/search/people/people_18.naver\"\r\n");
      out.write("								class=\"helpdesk\" target=\"_blank\">네이버 고객센터</a> <a nocr=\"\"\r\n");
      out.write("								onclick=\"fnLayerClose();return false;\" href=\"javascript:;\"\r\n");
      out.write("								class=\"closelayer C\"><img\r\n");
      out.write("								src=\"https://ssl.pstatic.net/sstatic/search/images11/btn_layer_close.gif\"\r\n");
      out.write("								width=\"10\" height=\"9\" alt=\"네이버 인물정보 도움말 닫기\"></a> <span\r\n");
      out.write("								class=\"arw detail C\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("				$Fn(fnLayerOpen).attach($('more_div_btn'), \"click\");\r\n");
      out.write("				function fnLayerOpen(e) {\r\n");
      out.write("					$('tooltip_layer').style.visibility = \"visible\";\r\n");
      out.write("					goOtherTCR(this,\r\n");
      out.write("							'a=nco_x29*3.imaginf&r=1&i=1800000D_00000008EF4D');\r\n");
      out.write("				}\r\n");
      out.write("				function fnLayerClose(e) {\r\n");
      out.write("					$('tooltip_layer').style.visibility = \"hidden\";\r\n");
      out.write("					$('more_div_btn').focus();\r\n");
      out.write("					goOtherTCR(this,\r\n");
      out.write("							'a=nco_x29*3.imaginfclose&r=1&i=1800000D_00000008EF4D');\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("			<a nocr=\"\"\r\n");
      out.write("				onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.profiledetail&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("				href=\"https://people.search.naver.com/search.naver?where=nexearch&amp;query=%EC%A7%80%EB%AF%BC&amp;sm=tab_etc&amp;ie=utf8&amp;key=PeopleService&amp;os=585549\"\r\n");
      out.write("				class=\"btn_txt_more\" target=\"_blank\"><span class=\"blind\">가수\r\n");
      out.write("					지민</span>인물정보 더보기</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			var __sDefaultPeopleTab = \"네이버TV\";\r\n");
      out.write("		</script>\r\n");
      out.write("		<div class=\"people_type\" id=\"tx_ca_people_workall\">\r\n");
      out.write("			<div class=\"texttab_type\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li id=\"tx_ca_people_tvcast_tab\" class=\"select\"><a nocr=\"1\"\r\n");
      out.write("						href=\"#\" class=\"pg_btn\">네이버TV</a></li>\r\n");
      out.write("					<li id=\"tx_ca_people_album_tab\"><a nocr=\"1\" href=\"#\"\r\n");
      out.write("						class=\"pg_btn\">앨범</a></li>\r\n");
      out.write("					<li id=\"tx_ca_people_play_tab\"><a nocr=\"1\" href=\"#\"\r\n");
      out.write("						class=\"pg_btn\">공연</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lst_cont tvcast \" style=\"display: block;\">\r\n");
      out.write("				<h3 class=\"blind\">네이버TV</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"thumb_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvcimg&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15564661\"> <img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=ofullfill_black&amp;size=128x72&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fphinf.pstatic.net%2Ftvcast%2F20200902_184%2FLscCY_1599034599472v79KI_JPEG%2FCA202009020064.jpg\"\r\n");
      out.write("								alt=\"[🔎실검돌] 한국 최초 빌보드 1위 가수 BTS! (BTS No.1 on Billboard HOT 100)🎉 항상 보라해💜 BTS 연도별 무대 모음 l #방탄소년단(BTS)\"\r\n");
      out.write("								width=\"128\" height=\"72\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"> <span class=\"ico_play\"></span> <span\r\n");
      out.write("								class=\"runtime\"><span class=\"bg\">재생시간</span><em>21분\r\n");
      out.write("										07초</em></span> <span class=\"img_bd\"></span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"txt_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvctit&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15564661\"\r\n");
      out.write("								class=\"cast_txt\">[🔎실검돌] 한국 최초 빌보드 1위 가수...</a> <span\r\n");
      out.write("								class=\"day_txt\">20시간 전</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"thumb_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvcimg&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15563635\"> <img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=ofullfill_black&amp;size=128x72&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fphinf.pstatic.net%2Ftvcast%2F20200902_10%2FJhH2P_1599032042770oysM3_JPEG%2F1599032028791.jpg\"\r\n");
      out.write("								alt=\"방탄소년단(BTS)도 '합성'인줄 알았다는 빌보드 1위 기념 소감 (글로벌 미디어데이)\"\r\n");
      out.write("								width=\"128\" height=\"72\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"> <span class=\"ico_play\"></span> <span\r\n");
      out.write("								class=\"runtime\"><span class=\"bg\">재생시간</span><em>3분\r\n");
      out.write("										26초</em></span> <span class=\"img_bd\"></span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"txt_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvctit&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15563635\"\r\n");
      out.write("								class=\"cast_txt\">방탄소년단(BTS)도 '합성'인줄 알았다는...</a> <span\r\n");
      out.write("								class=\"day_txt\">22시간 전</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"thumb_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvcimg&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15418757\"> <img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=ofullfill_black&amp;size=128x72&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fphinf.pstatic.net%2Ftvcast%2F20200825_5%2F6c2HY_1598281832959FMGjj_PNG%2F1598281810468.png\"\r\n");
      out.write("								alt=\"BTS (방탄소년단) 'Dynamite' Official MV (B-side)\" width=\"128\"\r\n");
      out.write("								height=\"72\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"> <span class=\"ico_play\"></span> <span\r\n");
      out.write("								class=\"runtime\"><span class=\"bg\">재생시간</span><em>3분\r\n");
      out.write("										47초</em></span> <span class=\"img_bd\"></span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"txt_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvctit&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15418757\"\r\n");
      out.write("								class=\"cast_txt\">BTS (방탄소년단) 'Dynamite' ...</a> <span\r\n");
      out.write("								class=\"day_txt\">2020.08.25.</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"thumb_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvcimg&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15369765\"> <img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=ofullfill_black&amp;size=128x72&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fphinf.pstatic.net%2Ftvcast%2F20200821_18%2FZOsCZ_1597993576818Xw8c6_JPEG%2F1597993227096.jpg\"\r\n");
      out.write("								alt=\"'3분 요약본' BTS(방탄소년단) 디지털 싱글 ‘Dynamite’ 글로벌 기자간담회\"\r\n");
      out.write("								width=\"128\" height=\"72\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"> <span class=\"ico_play\"></span> <span\r\n");
      out.write("								class=\"runtime\"><span class=\"bg\">재생시간</span><em>3분\r\n");
      out.write("										21초</em></span> <span class=\"img_bd\"></span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"txt_box\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvctit&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("								target=\"_blank\" href=\"https://tv.naver.com/v/15369765\"\r\n");
      out.write("								class=\"cast_txt\">'3분 요약본' BTS(방탄소년단) 디지털...</a> <span\r\n");
      out.write("								class=\"day_txt\">2020.08.21.</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<a nocr=\"\"\r\n");
      out.write("					onclick=\"return goOtherCR(this, 'a=nco_x29*3.tvcmore&amp;r=1&amp;i=1800000D_00000008EF4D&amp;u=' + urlencode(this.href));\"\r\n");
      out.write("					target=\"_blank\" class=\"more_view\"\r\n");
      out.write("					href=\"http://tv.naver.com/search/clip?query=지민&amp;sort=date\"><span\r\n");
      out.write("					class=\"blind\">네이버TV </span>더보기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lst_cont albumlist\" id=\"tx_ca_people_album_content\"\r\n");
      out.write("				style=\"display: none;\">\r\n");
      out.write("				<h3 class=\"blind\">앨범</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><div class=\"thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"https://vibe.naver.com/album/4820425\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=o&amp;size=78x71&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fmusicmeta-phinf.pstatic.net%2Falbum%2F004%2F820%2F4820425.jpg%3Ftype%3Dr204Fll%26v%3D20200828115809\"\r\n");
      out.write("								alt=\"Dynamite\" width=\"78\" height=\"71\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"><img height=\"75\" width=\"84\" class=\"bg_album\"\r\n");
      out.write("								alt=\"\"\r\n");
      out.write("								src=\"https://ssl.pstatic.net/sstatic/search/images11/blank.gif\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dt>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"https://vibe.naver.com/album/4820425\" target=\"_blank\">Dynamite</a>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd>방탄소년단</dd>\r\n");
      out.write("							<dd>2020.08.21</dd>\r\n");
      out.write("						</dl></li>\r\n");
      out.write("					<li><div class=\"thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"https://vibe.naver.com/album/4600107\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=o&amp;size=78x71&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fmusicmeta-phinf.pstatic.net%2Falbum%2F004%2F600%2F4600107.jpg%3Ftype%3Dr204Fll%26v%3D20200715112013\"\r\n");
      out.write("								alt=\"MAP OF THE SOUL : 7 ~THE JOURNEY~\" width=\"78\" height=\"71\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"><img height=\"75\" width=\"84\" class=\"bg_album\"\r\n");
      out.write("								alt=\"\"\r\n");
      out.write("								src=\"https://ssl.pstatic.net/sstatic/search/images11/blank.gif\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dt>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"https://vibe.naver.com/album/4600107\" target=\"_blank\"\r\n");
      out.write("									title=\"MAP OF THE SOUL : 7 ~THE JOURNEY~\">MAP OF TH...</a>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd>방탄소년단</dd>\r\n");
      out.write("							<dd>2020.07.15</dd>\r\n");
      out.write("						</dl></li>\r\n");
      out.write("					<li><div class=\"thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"https://vibe.naver.com/album/4417123\" target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=o&amp;size=78x71&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fmusicmeta-phinf.pstatic.net%2Falbum%2F004%2F417%2F4417123.jpg%3Ftype%3Dr204Fll%26v%3D20200709150702\"\r\n");
      out.write("								alt=\"MAP OF THE SOUL : 7\" width=\"78\" height=\"71\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"><img height=\"75\" width=\"84\" class=\"bg_album\"\r\n");
      out.write("								alt=\"\"\r\n");
      out.write("								src=\"https://ssl.pstatic.net/sstatic/search/images11/blank.gif\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dt>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.albumtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"https://vibe.naver.com/album/4417123\" target=\"_blank\"\r\n");
      out.write("									title=\"MAP OF THE SOUL : 7\">MAP OF TH...</a>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd>방탄소년단</dd>\r\n");
      out.write("							<dd>2020.02.21</dd>\r\n");
      out.write("						</dl></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<a nocr=\"\"\r\n");
      out.write("					onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.wtmusicmore&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("					class=\"more_view\"\r\n");
      out.write("					href=\"https://vibe.naver.com/artist/143179/albums\" target=\"_blank\"><span\r\n");
      out.write("					class=\"blind\">앨범 </span>더보기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lst_cont\" id=\"tx_ca_people_play_content\"\r\n");
      out.write("				style=\"display: none;\">\r\n");
      out.write("				<h3 class=\"blind\">공연</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"big_thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"https://kr.lottedfs.com/event/familyconcert\"\r\n");
      out.write("								target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=mfullfill&amp;size=66x80&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fdbscthumb-phinf.pstatic.net%2F4209_000_16%2F20200831165238821_ZBUOA3WDL.jpg%2F%25EC%25A0%259C%2B30%25ED%259A%258C.jpg%3Ftype%3Dr160\"\r\n");
      out.write("								alt=\"제 30회 롯데면세점 랜선 패밀리 콘서트\" width=\"66\" height=\"80\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"https://kr.lottedfs.com/event/familyconcert\"\r\n");
      out.write("									target=\"_blank\" title=\"제 30회 롯데면세점 랜선 패밀리 콘서트\">제 30회 롯데면...</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>2020.09.27.</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"big_thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"http://ticket.interpark.com/Gate/OtherSite/NaverTotalSearchGate.asp?fn=goodsdetail&amp;r1=19011533\"\r\n");
      out.write("								target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=mfullfill&amp;size=66x80&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fdbscthumb-phinf.pstatic.net%2F4209_000_2%2F20190814173536298_PRWFLWA1I.png%2FBTS%2BWORLD%2BTOUR.png%3Ftype%3Dr160\"\r\n");
      out.write("								alt=\"BTS WORLD TOUR 'LOVE YOURSELF: SPEAK YOURSELF' [THE FINAL]\"\r\n");
      out.write("								width=\"66\" height=\"80\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"http://ticket.interpark.com/Gate/OtherSite/NaverTotalSearchGate.asp?fn=goodsdetail&amp;r1=19011533\"\r\n");
      out.write("									target=\"_blank\" title=\"BTS WORLD TOUR \" love=\"\" yourself:=\"\"\r\n");
      out.write("									speak=\"\" yourself'=\"\" [the=\"\" final]'=\"\">BTS WORLD...</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dt>잠실종합운동장 주경기장</dt>\r\n");
      out.write("							<dd>2019.10.26. ~ 2019.10.29.</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"last\">\r\n");
      out.write("						<div class=\"big_thumb\">\r\n");
      out.write("							<a nocr=\"\"\r\n");
      out.write("								onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playimage&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("								href=\"https://kr.lottedfs.com/event/familyconcert\"\r\n");
      out.write("								target=\"_blank\"><img\r\n");
      out.write("								src=\"https://search.pstatic.net/common?type=mfullfill&amp;size=66x80&amp;quality=95&amp;direct=true&amp;src=https%3A%2F%2Fdbscthumb-phinf.pstatic.net%2F4209_000_2%2F20190624154852832_0K290MRUG.PNG%2F%25EB%25A1%25AF%25EB%258D%25B0.PNG%3Ftype%3Dr160\"\r\n");
      out.write("								alt=\"LOTTE DUTY FREE FAMILY CONCERT\" width=\"66\" height=\"80\"\r\n");
      out.write("								onerror=\"tx_noimage_thumb(this, 'sp_noimg', 'https://ssl.pstatic.net/sstatic/search/images11/blank.gif');\"\r\n");
      out.write("								class=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<dl>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a nocr=\"\"\r\n");
      out.write("									onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.playtitle&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("									class=\"sh_people_title sh_people_link\"\r\n");
      out.write("									href=\"https://kr.lottedfs.com/event/familyconcert\"\r\n");
      out.write("									target=\"_blank\" title=\"LOTTE DUTY FREE FAMILY CONCERT\">LOTTE\r\n");
      out.write("									DUT...</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dt>KSPO DOME</dt>\r\n");
      out.write("							<dd>2019.08.09. ~ 2019.08.11.</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<a nocr=\"\"\r\n");
      out.write("					onclick=\"return goOtherCR(this, 'u='+urlencode(this.href)+'&amp;r=1&amp;a='+nco_area_585549+'.wtplaymore&amp;i='+'1800000D_00000008EF4D');\"\r\n");
      out.write("					class=\"more_view\"\r\n");
      out.write("					href=\"https://people.search.naver.com/search.naver?where=nexearch&amp;query=%EC%A7%80%EB%AF%BC&amp;sm=tab_etc&amp;ie=utf8&amp;key=PeopleService&amp;os=585549\"\r\n");
      out.write("					target=\"_blank\"><span class=\"blind\">공연 </span>더보기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			nhn.peopleTabView = function(a) {\r\n");
      out.write("				var d = a;\r\n");
      out.write("				for (var b = 0, c = d.length; b < c; b++) {\r\n");
      out.write("					new nhn.peopleTabView.Tab(d[b]);\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			nhn.peopleTabView.Tab = $Class({\r\n");
      out.write("				$init : function(b) {\r\n");
      out.write("					var a = $$.getSingle(\">div.texttab_type>ul\", b);\r\n");
      out.write("					this.aTab = $$(\">li>a\", a);\r\n");
      out.write("					this.aLayer = $$(\">div.lst_cont\", b);\r\n");
      out.write("					this.htClickArea = {\r\n");
      out.write("						\"영화\" : \"nco_x29*3.wtmovie\",\r\n");
      out.write("						\"앨범\" : \"nco_x29*3.wtmusic\",\r\n");
      out.write("						\"선거이력\" : \"nco_x29*3.telection\",\r\n");
      out.write("						\"경기성적\" : \"nco_x29*3.wtsports\",\r\n");
      out.write("						\"공연\" : \"nco_x29*3.wtplay\",\r\n");
      out.write("						\"주요근황\" : \"nco_x29*3.wtrecent\",\r\n");
      out.write("						\"방송\" : \"nco_x29*3.wtonair\",\r\n");
      out.write("						\"도서\" : \"nco_x29*3.wtbook\",\r\n");
      out.write("						\"웹툰\" : \"nco_x29*3.wtwebtoon\",\r\n");
      out.write("						\"미술작품\" : \"nco_x29*3.wtarts\",\r\n");
      out.write("						\"사진작품\" : \"nco_x29*3.wtphoto\",\r\n");
      out.write("						\"칼럼\" : \"nco_x29*3.wtcolumn\",\r\n");
      out.write("						\"네이버TV\" : \"nco_x29*3.tvc\",\r\n");
      out.write("						\"그라폴리오\" : \"nco_x29*3.gra\",\r\n");
      out.write("						\"아트\" : \"nco_x29*3.art\",\r\n");
      out.write("						\"명언\" : \"nco_x29*3.quotation\",\r\n");
      out.write("						\"지식iN\" : \"nco_x29*3.wtkin\",\r\n");
      out.write("						\"전시\" : \"nco_x29*3.exh\"\r\n");
      out.write("					};\r\n");
      out.write("					$Fn(this.click, this).attach(a, \"click\");\r\n");
      out.write("					this.initTab();\r\n");
      out.write("				},\r\n");
      out.write("				click : function(a) {\r\n");
      out.write("					a.stop();\r\n");
      out.write("					var d = a.element;\r\n");
      out.write("					if (d.tagName == \"A\") {\r\n");
      out.write("						for (var c = 0, f = this.aTab.length; c < f; c++) {\r\n");
      out.write("							var b = $Element(this.aTab[c]).parent();\r\n");
      out.write("							if (this.aTab[c] == d) {\r\n");
      out.write("								if (!b.hasClass(\"select\")) {\r\n");
      out.write("									b.addClass(\"select\");\r\n");
      out.write("								}\r\n");
      out.write("								$Element(this.aLayer[c]).show();\r\n");
      out.write("								nhn.common.ellipsis(this.aLayer[c]);\r\n");
      out.write("							} else {\r\n");
      out.write("								b.removeClass(\"select\");\r\n");
      out.write("								$Element(this.aLayer[c]).hide();\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("						try {\r\n");
      out.write("							for ( var c in this.htClickArea) {\r\n");
      out.write("								if (d.innerHTML.match(new RegExp(c))) {\r\n");
      out.write("									goOtherTCR(\r\n");
      out.write("											this,\r\n");
      out.write("											(\"a=\" + this.htClickArea[c]\r\n");
      out.write("													+ \"&r=1&i=\" + txinfo_people_gdid));\r\n");
      out.write("									break;\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						} catch (g) {\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				initTab : function() {\r\n");
      out.write("					try {\r\n");
      out.write("						if (__sDefaultPeopleTab && __sDefaultPeopleTab != \"\") {\r\n");
      out.write("							for (var b = 0, c = this.aTab.length; b < c; b++) {\r\n");
      out.write("								var a = $Element(this.aTab[b]).parent();\r\n");
      out.write("								if ($Element(this.aTab[b]).html().match(\r\n");
      out.write("										__sDefaultPeopleTab)) {\r\n");
      out.write("									if (!a.hasClass(\"select\")) {\r\n");
      out.write("										a.addClass(\"select\");\r\n");
      out.write("									}\r\n");
      out.write("									$Element(this.aLayer[b]).show();\r\n");
      out.write("								} else {\r\n");
      out.write("									a.removeClass(\"select\");\r\n");
      out.write("									$Element(this.aLayer[b]).hide();\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					} catch (d) {\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			if ($(\"tx_ca_people_workall\")) {\r\n");
      out.write("				var aPeopleType = [ $(\"tx_ca_people_workall\") ];\r\n");
      out.write("				nhn.peopleTabView(aPeopleType);\r\n");
      out.write("			} else {\r\n");
      out.write("				$Fn(function() {\r\n");
      out.write("					var a = [ $(\"tx_ca_people_workall\") ];\r\n");
      out.write("					nhn.peopleTabView(a);\r\n");
      out.write("				}).attach(window, \"load\");\r\n");
      out.write("			}\r\n");
      out.write("			var elTxCaPeopleKinContent = $(\"tx_ca_people_kin_content\");\r\n");
      out.write("			if (elTxCaPeopleKinContent)\r\n");
      out.write("				nhn.common.ellipsis(elTxCaPeopleKinContent);\r\n");
      out.write("		</script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			function tx_noimage_thumb(img, className, noimage) {\r\n");
      out.write("				img.onerror = null;\r\n");
      out.write("				if (noimage) {\r\n");
      out.write("					img.src = noimage;\r\n");
      out.write("				} else {\r\n");
      out.write("					img.src = \"https://ssl.pstatic.net/sstatic/search/images11/blank.gif\";\r\n");
      out.write("				}\r\n");
      out.write("				if (img.alt == '') {\r\n");
      out.write("					img.alt = \"이미지 준비중\";\r\n");
      out.write("				} else {\r\n");
      out.write("					img.alt = img.alt + \" 준비중\";\r\n");
      out.write("				}\r\n");
      out.write("				if (className) {\r\n");
      out.write("					img.className = className;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			function tx_set_href(a) {\r\n");
      out.write("				if (a.href)\r\n");
      out.write("					a.href = a.href.replace(/&query=[^&]*/g, \"&query=\"\r\n");
      out.write("							+ headerfooter_query_encoded_utf8);\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
